Consider no_color environment variable
fredmorcos/tvrank pull request #27
Opened 2022-03-10 23:41 UTC by caglaryucekaya

Resolves #14

2022-03-11 05:57 UTC, fredmorcos requested changes
Thank you so much, this is really awesome! 👍🏽 A few small changes and it can be merged 😃

2022-03-11 05:57 UTC, fredmorcos commented on src/main.rs
> +  let color: bool = env::var("NO_COLOR").is_err() || opt.color;
Can you move this to `main()` instead? Perhaps something like `color: env::var("NO_COLOR").is_err() || opts.color || opt.opts.color`?

2022-03-11 05:57 UTC, fredmorcos commented on src/search.rs
> +    },
Could you put this `if ... else ...` in a `macro_rules! make_bold` above that takes the `$title` and `$color` as arguments?

2022-03-11 05:57 UTC, fredmorcos commented on src/search.rs
You can put the macro here.

2022-03-11 15:48 UTC, caglaryucekaya commented
Done! Hope I didn't misunderstand where to declare the macro. If so, I'll move it.

2022-03-12 08:07 UTC, fredmorcos approved these changes
Awesome, thank you! 👍🏽

2022-03-12 08:07 UTC, merged