Support JSON output
fredmorcos/tvrank pull request #35
Opened 2022-03-14 17:55 UTC by Olsi-B

Solves #17.
This also contains some refactoring.

2022-03-15 19:54 UTC, fredmorcos requested changes
So I think this is a really good start! It needs some more work and refinement, I feel like there are too many `struct`s that were added which could have been avoided by simply reusing what was already there (e.g. `SearchRes`).

What are your thoughts on this?

BTW, if you would also like, we can have a Zoom/Jitsi call to discuss this more directly. Or even perhaps work together on the PR.

2022-03-15 19:54 UTC, fredmorcos commented on src/print.rs
> +    println!("{}", serde_json::to_string_pretty(&all_results).expect("Could not print"));
Perhaps use a `?` instead of the `expect(...)` call here?

2022-03-15 19:54 UTC, fredmorcos commented on src/print.rs
> +    }
I feel like this loop ought to be avoided. As in, we shouldn't need to loop over the results until we're printing them. Am I missing something?

2022-03-15 19:54 UTC, fredmorcos commented on src/print.rs
> +}
Can't we just make `ImdbTitle` serializable instead?

2022-03-15 19:54 UTC, fredmorcos commented on src/print.rs
> +    };
All the `String::from("")` which get overwritten immediately after are an indication of a deeper design issue (i.e. a code smell).

Could you explain why we need `JsonResult` at all?

2022-03-15 19:54 UTC, fredmorcos commented on src/main.rs
> +
A gut feeling tells me `structopt` should be able to support having an `OutputFormat` here instead of a `String`. Also, the help text just says that "table" is the default but does not tell the user what other available values `--output` can accept.

2022-03-15 19:54 UTC, fredmorcos commented on src/print.rs
> +}
I feel like `SearchRes` could have taken on this role...

2022-03-15 19:54 UTC, fredmorcos commented on src/print.rs
> +    series_results: Option<&[&ImdbTitle]>,
I don't think these need to be `Option<...>` here since the JSON output still contains `"series": []` when series are not provided.

2022-03-15 21:51 UTC, Olsi-B commented
> BTW, if you would also like, we can have a Zoom/Jitsi call to discuss this more directly.

Yes, a call would be a good idea to discuss and clarify some of the points you have made.

2022-03-16 18:24 UTC, Olsi-B commented on src/print.rs
> +    };
I needed owned values to work with the formatting and I can't use `String` properties in `ImdbTitle`. A better name name for this would be `OutputResult`, as Yaml output would use the same structure.

2022-03-16 18:27 UTC, Olsi-B commented on src/print.rs
> +    series_results: Option<&[&ImdbTitle]>,
Without `Option` you will get the "Found 0 series." message when you search with the `movies` sub-command.

2022-03-16 18:29 UTC, Olsi-B commented on src/print.rs
> +}
See below.

2022-03-16 19:36 UTC, Olsi-B commented on src/main.rs
> +
Updated.

2022-03-18 19:35 UTC, fredmorcos commented
Amazing work! I really love it! Thank you very much!!!

Resolve the conflicts and we can merge it.

2022-03-18 20:38 UTC, fredmorcos approved these changes

2022-03-18 20:41 UTC, Olsi-B commented
Conflicts resolved.

2022-03-18 20:57 UTC, merged